<?php
/**
 * Created by PhpStorm.
 * User: vadim
 * Date: 07.03.16
 * Time: 1:46
 */

namespace sibds\grid;

use yii\helpers\Html;
use kartik\icons\Icon;


class GridView extends \kartik\grid\GridView
{
    use TranslateTrait;

    public $containerOptions = ['style' => 'overflow: auto']; // only set when $responsive = false
    public $headerRowOptions = ['class' => 'kartik-sheet-style'];
    public $filterRowOptions = ['class' => 'kartik-sheet-style'];

    public $pjax = true; // pjax is set to always true for this demo

    // set export properties
    public $export = [
        'fontAwesome' => false
    ];

    // parameters from the demo form
    public $bordered = true;
    public $striped = false;
    public $condensed = true;
    public $responsive = true;
    public $hover = true;
    public $floatHeader = true;
    public $showPageSummary = false;
    public $panel = [
        //'type' => GridView::TYPE_PRIMARY,
        'heading' => false,//$this->title,
    ];
    public $panelAfterTemplate = '{summary}{after}';
    public $panelBeforeTemplate = <<< HTML
    <div class="float-left">
        {before}
        {summary}
    </div>
    <div class="float-right">
        <div class="btn-toolbar kv-grid-toolbar" role="toolbar">
            {toolbar}
        </div>
    </div>    
    <div class="clearfix"></div>
HTML;
    public $persistResize = false;

    public function init()
    {
        $this->registerTranslations();

        //Toolbar
        $toolbar = [
            '{export}',
            '{toggleData}',
        ];

        $view = $this->getView();

        $basic_toolbar = [
            ['content' =>
                Html::a(self::show('plus') . self::t('toolbar', 'Add'), ['update'], ['data-pjax' => 0, 'title' => 'Add Pages', 'class' => 'btn btn-success']) . ' ' .
                Html::a(self::show('sync') . self::t('toolbar', 'Refresh'), [\Yii::$app->controller->defaultAction], ['data-pjax' => 0, 'class' => 'btn btn-default', 'title' => 'Reset Grid'])
            ],
        ];

        if(!is_null($this->filterModel)){
            if($this->filterModel->hasAttribute('category_id')||
                $this->filterModel->hasMethod('getCategory')){
                array_push($basic_toolbar,
                    [
                        'content' =>
                            Html::a(self::show('list') . self::t('toolbar', 'Categories'),
                                [\Yii::$app->controller->id.'-category/list'],
                                ['data-pjax' => 0, 'title' =>  self::t('toolbar', 'Categories'),
                                    'class' => 'btn btn-default'])
                    ]
                );
            }
            
            if($this->filterModel->hasAttribute('group_id')||
                $this->filterModel->hasMethod('getGroup')){
                array_push($basic_toolbar,
                    [
                        'content' =>
                            Html::a(self::show('list') . self::t('toolbar', 'Groups'),
                                [\Yii::$app->controller->id.'-group/list'],
                                ['data-pjax' => 0, 'title' => self::t('toolbar', 'Groups'),
                                    'class' => 'btn btn-default'])
                    ]
                );
            }


            if($this->filterModel->hasAttribute($this->filterModel->removedAttribute)){
                array_push($basic_toolbar,
                    [
                        'content' =>
                            Html::a(
                                self::show('trash') . self::t('toolbar', 'In Trash'),
                                ['trash'],
                                ['data-pjax' => 0, 'title' => 'Removed records', 'class' => 'btn btn-default'])
                    ]
                    );
            }    
        }
        


        if ($view->context->action->id === 'trash') {
            $basic_toolbar = [
                [
                    'content' =>
                        Html::a(
                            self::show('long-arrow-alt-left') . self::t('toolbar', 'Back to Records'),
                            ['list'],
                            ['data-pjax' => 0, 'title' => 'List records', 'class' => 'btn btn-default'])
                ]
            ];
        }
        $toolbar = \yii\helpers\ArrayHelper::merge($basic_toolbar, $toolbar);

        $this->toolbar = $toolbar;

        return parent::init(); // TODO: Change the autogenerated stub
    }

    private static function show($name){
        return '<span class="fas fa-'.$name.'"></span>&nbsp;';
    }
}
