<?php
/**
 * Created by PhpStorm.
 * User: vadim
 * Date: 13.02.16
 * Time: 15:12
 */

namespace sibds\grid;


use kartik\icons\Icon;
use kartik\grid\DataColumn;
use yii\helpers\Html;

class UrlColumn extends DataColumn
{
    use TranslateTrait;

    public $format = 'raw';
    public $showLock = false;

    public function init()
    {
        Icon::map($this->grid->getView());
        $this->registerTranslations();

        parent::init(); // TODO: Change the autogenerated stub

        $this->value = function ($model, $key, $index, $widget) {
            $lockIcon = '';

            if($this->showLock){
                if($model->hasAttribute('locked')&&$model->{$model->lockedAttribute}){
                    $lockIcon = Icon::show('eye-slash');
                }else{
                    $lockIcon = Icon::show('eye');
                }
            }

            return Html::a($lockIcon.$model->{$this->attribute},
                ['update', 'id'=>$model->id],
                ['title'=>self::t('messages', 'Edit item'), 'data-pjax'=>0]);
        };
    }

}
