<?php
/**
 * Created by PhpStorm.
 * User: vadim
 * Date: 13.02.16
 * Time: 15:12
 */

namespace sibds\grid;


use yii\grid\DataColumn;
use yii\helpers\Html;

class UrlColumn extends DataColumn
{
    public $format = 'raw';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->value = function ($model, $key, $index, $widget) {
            return Html::a($model->{$this->attribute},
                ['update', 'id'=>$model->id],
                ['title'=>'Редактирование записи']);
        };
    }
}