<?php
/**
 * Created by PhpStorm.
 * User: vadim
 * Date: 13.02.16
 * Time: 15:12
 */

namespace sibds\grid;


use kartik\icons\Icon;
use kartik\grid\DataColumn;
use yii\helpers\Html;

class UrlColumn extends DataColumn
{
    use TranslateTrait;

    public $action = 'update';

    public $format = 'raw';
    public $showLock = false;

    public function init()
    {
        $this->registerTranslations();

        parent::init(); // TODO: Change the autogenerated stub

        if(empty($this->value))
            $this->value = function ($model, $key, $index, $widget) {
                $lockIcon = '';

                if($this->showLock){
                    if($model->hasAttribute('locked')&&$model->{$model->lockedAttribute}){
                        $lockIcon = self::show('eye-slash');
                    }else{
                        $lockIcon = self::show('eye');
                    }
                }

                return Html::a($lockIcon.$model->{$this->attribute},
                    [$this->action, 'id'=>$model->id],
                    ['title'=>self::t('messages', 'Edit item'), 'data-pjax'=>0]);
            };
    }

    private static function show($name){
        return '<span class="fas fa-'.$name.'"></span>&nbsp;';
    }
}
